name: Build

on:
  workflow_dispatch:
    inputs:
      target:
        description: 'Target (Debug, Release)'
        required: true
        default: 'Release'

jobs:
  build-suite:
    name: Build
    runs-on: windows-latest

    steps:
    - name: Intallation Type
      shell: powershell
      run: |
        Write-Host "WINDOWS INSTALLATION TYPE: $((Get-ItemProperty -Path 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion').InstallationType)"
    
    # Checkout repository
    - uses: actions/checkout@v3

    # Run build
    - name: Build
      run: dotnet build --configuration Release

    # Run test
    - name: Run tests
      shell: powershell
      run: |
        $tests = Get-ChildItem -recurse -file *Tests.dll | Where-Object { $_.FullName -notmatch "\\obj\\|Automation" } | ForEach-Object FullName
        Write-Host "Discovered tests: $tests"
        dotnet vstest $tests /Framework:".NETFramework,Version=v4.8" /logger:"console;verbosity=normal"

    # Upload artifacts
    - uses: actions/upload-artifact@v3
      with:
        name: Artifacts
        path: ${{ github.workspace }}\artifacts\*